In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


### list vs numpy array

In [8]:
py_list = [1,2,4,5]
# print(f"Python list multi {py_list*2}")

np_array = np.array([1,2,4,5])

# print(f"Numpy array multi {np_array*2}")


import time

start = time.time()
py_list = [x*2 for x in range(100000000)]
end = time.time()
print(f"Python list time {end-start}")


start = time.time()
np_array = np.arange(100000000)*2
end = time.time()
print(f"Numpy array time {end-start}")

Python list time 5.561312198638916
Numpy array time 2.729395866394043


### creating array from scratch

In [8]:
# zeros = np.zeros((10000,10000))
# print(zeros)

# ones = np.ones((10000,10000))
# print(ones)


full = np.full((1000,10000),10000)
# print(full)

# random = np.random.random((10000,10000))
# print(random)

sequence = np.arange(0, 10,2)
print(sequence)

[0 2 4 6 8]


### vector, Matrix and Tensor

In [ ]:
vector = np.array([1,2,3])
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vector)
print(matrix)
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


### Array Propertiens

In [12]:
arr = np.array([[1,2,3],
                [4,5,6]
                ])
print(f"shape of array {arr.shape}")
print(f"shape of array {arr.ndim}")
print(f"shape of array {arr.size}")
print(f"shape of array {arr.dtype}")


shape of array (2, 3)
shape of array 2
shape of array 6
shape of array int64


### Array Reshaping

In [19]:
arr = np.arange(12)
print(f"original array {arr}")
reshape = arr.reshape((3,4))
print(f"reshaped array {reshape}")

flattened = reshape.flatten()
print(f"Flattened array {flattened}")

raveled = reshape.ravel()
print(f"raveled array {raveled}")

# transpose

transpose = reshape.T
print(f"transpose {transpose}")

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Phase2


### numpy Array operations

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# print(f"Basic Slicing {arr[2:7]}")
# print(f"with step {arr[1:8:2]}")

print(f"reverse {arr[::-1]}")


reverse [10  9  8  7  6  5  4  3  2  1]


In [27]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]
                   ])
# print(arr_2d)
print(f"specific element {arr_2d[2,0]}")
print(f"entire row {arr_2d[2]}")
print(f"entire column {arr_2d[:,2]}")

specific element 7
entire row [7 8 9]
entire column [3 6 9]


### sorting ---------------- 

In [ ]:
unsorted = np.array([5,4,3,2,1])
sorted = np.sort(unsorted)

print(f"unsorted {unsorted}")
print(f"sorted {sorted}")

arr_2d_unsorted = np.array([[23,2,3],
                            [4,5,6],
                            [7,8,9]
                            ])

arr_2d_sorted = np.sort(arr_2d_unsorted, axis=0) 
# axis <-> 0->for column 1->for row

print(f"unsorted {arr_2d_unsorted}")
print(f"sorted {arr_2d_sorted}")

unsorted [5 4 3 2 1]
sorted [1 2 3 4 5]
unsorted [[23  2  3]
 [ 4  5  6]
 [ 7  8  9]]
sorted [[ 4  2  3]
 [ 7  5  6]
 [23  8  9]]


### filtering

In [ ]:
numbers  = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2==0]
# print(f"original array {numbers}")
# print(f"even number {even_number}")


original array [ 1  2  3  4  5  6  7  8  9 10]
even number [ 2  4  6  8 10]


### Filter with mask

In [47]:
mask = numbers > 5

print(f"original array {numbers[mask]}")

original array [ 6  7  8  9 10]


### fancy indexing vs np.where()

In [49]:
indices = [1,3,5,7,9]

print(f"original array {numbers[indices]}")

where_result = np.where(numbers > 5)

print(f"original array {numbers[where_result]}")

original array [ 2  4  6  8 10]
original array [ 6  7  8  9 10]


In [51]:
condition_array = np.where(numbers > 5, "true","false")

print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


Adding and Removing Data

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([10,9,8,7,6,5,4,3,2,1])
# combine = arr1 + arr2 # add both array
combine = np.concatenate((arr1,arr2))

print(combine)

# print(f"mean {np.mean(arr)}")
# print(f"median {np.median(arr)}")
# print(f"std {np.std(arr)}")
# print(f"var {np.var(arr)}")
# print(f"sum {np.sum(arr)}")
# print(f"min {np.min(arr)}")
# print(f"max {np.max(arr)}")

[ 1  2  3  4  5  6  7  8  9 10 10  9  8  7  6  5  4  3  2  1]


### array compatibility

In [53]:
a = np.array([1,2,3,])
b = np.array([4,5,6])
c = np.array([7,8,9])

print(f"compatibility shapes { a.shape == b.shape}")
print(f"compatibility shapes { a.shape == c.shape}")


compatibility shapes True
compatibility shapes True


In [60]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
new_col = np.array([[7],[8]])

with_new_row = np.vstack((original,new_row))
with_new_col = np.hstack((original,new_col,))

print(f"with new row {with_new_row}")
print(f"with new col {with_new_col}")

with new row [[1 2]
 [3 4]
 [5 6]]
with new col [[1 2 7]
 [3 4 8]]


In [62]:
arr  = np.array([1,2,3,4,5,6,7,8,9,10])
deleted = np.delete(arr,3)

print(f"original array {arr}")
print(f"deleted array {deleted}")

original array [ 1  2  3  4  5  6  7  8  9 10]
deleted array [ 1  2  3  5  6  7  8  9 10]
